### ISSUE TITLE
There is an extra closing single quote and parenthesis when complete and there are already ones in place

### ISSUE THREAD

**Issue by feryardiant** [RicardoRamirezR/blade-nav.nvim#25] opened 2024-09-17 17:47 UTC
Just trying out this plugin based on [this recommendation](https://github.com/EmranMR/tree-sitter-blade/discussions/72#discussioncomment-10671406) and immediately noticed that when I type `@route('` and select one of the options it replace existing text with `route('route.name')')` including the closing single quote and parenthesis.

https://github.com/user-attachments/assets/14829473-3302-42f3-8e09-1b95cf148f2e

Is there any option to only inserting the `route.name`?

**Comment by RicardoRamirezR** [comment] 2024-09-17 23:08
Hi @feryardiant the issue is your auto close feature that I do not use.

The issue can be solve by  adding an option like `close_tag_on_complete` that you can turn off by setting it to false, that way the text is replaced but it wont include the closing `')`

**Comment by RicardoRamirezR** [comment] 2024-09-17 23:26
Check main.

the config:

```lua {
  "ricardoramirezr/blade-nav.nvim",
  ft = { "blade", "php" },
  opts = {
    close_tag_on_complete = false,
  },
}

It will be in the next release.

```

**Comment by cbaconnier** [comment] 2024-10-23 18:05
Hey @RicardoRamirezR, I think `not_close_tag` is always `false` even with the option.

```lua
M.not_close_tag = not (opts.close_tag_on_complete or true)

-- M.not_close_tag = not (false or true)
-- M.not_close_tag = not (true)
-- M.not_close_tag = false
```

I don't know lua yet, but if you  give me some time, I may PR  a fix.

**Comment by RicardoRamirezR** [comment] 2024-10-23 20:05
@cbaconnier nice catch. Over looked the expression, take your time

**Closed** 2024-10-24 20:09 UTC
